#! /bin/sh


# Autostart
sxhkd &

# run the xrandr command if an external monitor is connected to the laptop. this must be executed before the polybar command, so that polybar can set the two separate bars properly.
if [ -x /usr/bin/dual_monitor ];then
		sh dual_monitor
fi

#if [ -x /usr/bin/polybar ];
#	bash $HOME/.config/polybar/launch.sh
#fi

~/.config/polybar/launch.sh &
systemctl --user --now start greenclip.service &
sxhkd &

# Workspaces
bspc monitor DP-1 -d 1 2 3 4 5 
bspc monitor HDMI-1 -d 6 7 8 9 0


# Source the colors
source "${HOME}/.cache/wal/colors.sh"

# Set the border colors
bspc config normal_border_color "$color3"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"

# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"


# Borders and Gaps
bspc config border_width         0
bspc config window_gap           4 

bspc config bottom_padding 5
bspc config top_padding 27

bspc config split_ratio          0.60
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true

bspc config border_radius 10

# Rules
bspc config external_rules_command "$(which ~/.config/bspwm/bspwm-rules)"
 


